---
- name: Configure Minio Client
  hosts: 10.10.5.182
  gather_facts: no
  tasks:
    - name: Configure Minio client
      win_shell: |
        mc config host add minio https://10.10.5.182 minioadmin minio_admin
      become: yes
